[package]
name = "p2d_opb"
description = "A representation of OPB formulas"
version = "0.2.0"
edition = "2024"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/TUBS-ISF/p2d.git"
workspace = ".."

[dependencies]
bimap = "0.6"
pest = "2"
pest_derive = "2"
